# This file is auto-generated by OpenAPI Generator (https://openapi-generator.tech)
# Please replace "TEST_VALUE" with a proper value and uncomment the code for testing the function

Describe 'Org.OpenAPITools DefaultApi' {
    Context 'DefaultApi' {
        It 'Invoke-DefaultApiAddPet' {
            $ret = Invoke-PetApiGetPetById -newPet "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'DefaultApi' {
        It 'Invoke-DefaultApiDeletePet' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'DefaultApi' {
        It 'Invoke-DefaultApiFindPetById' {
            $ret = Invoke-PetApiGetPetById -id "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

    Context 'DefaultApi' {
        It 'Invoke-DefaultApiFindPets' {
            $ret = Invoke-PetApiGetPetById -tags "TEST_VALUE" -limit "TEST_VALUE"
            #$ret | Should BeOfType Org.OpenAPITools.Model.ModelNameHere
            #$ret.property | Should Be 0
        }
    }

}
